### ISSUE TITLE
Deprecation warning due to an old version of ember-cli-htmlbars

### ISSUE THREAD

**Issue by arnaudbesnier** [lynnetye/ember-trix-editor#12]
Hi,

Here is the warning, I have when I start my ember app using your package:
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
```

This warning is generated by an old version of `ember-cli-htmlbars` you use (0.7.9).
Can you update to a version 1.x to make it disappear.

See more info in this issue: https://github.com/ember-cli/ember-cli-htmlbars/issues/77

Thank you!

**Comment by arnaudbesnier** [comment]
cf. https://github.com/lynnetye/ember-trix-editor/pull/10

Can you please merge the PR?
👍

**Comment by channingallen** [comment]
Just reviewed it and merged. Good catch, and thanks for the contribution @arnaudbesnier!

**Comment by arnaudbesnier** [comment]
Thank you, can you release a new version of the npm package?

**Comment by channingallen** [comment]
Are referring to the following app version in the package manifest, or something else?

![image](https://cloud.githubusercontent.com/assets/3497287/19312789/f35524b8-9061-11e6-9db7-28a51744aeb6.png)

**Comment by arnaudbesnier** [comment]
I mean you need to bump to a new version of the package (for example: 1.0.6) and then publish it: https://docs.npmjs.com/cli/publish

Thank you!

**Comment by lynnetye** [comment]
@arnaudbesnier Version patch has been published! 👍
