### ISSUE TITLE
Setting actions

### ISSUE THREAD

**Issue by eliotpiering** [lynnetye/ember-trix-editor#2]
I was having trouble getting the trix-change event to work for me.  I'm not sure exactly how the actions were intended to work in this component;  it seemed like the component expects an action properties to be set as functions instead of as strings.  If this is the only way this works maybe this should be documented.  I made a pull request that just changed the one action to work like I expected where the component calls sendAction with the name of the action, (mostly I just needed to get this working now so I wouldn't expect this pull request to get merged in).  Please let me know where I was going wrong with this and what I should be setting for the action properties.  The component has been working great otherwise.  Thanks

**Comment by lynnetye** [comment]
@eliotpiering You can still use the approach of passing down the action name as a string and then sending up an action back up to call the original action handler function. However, our editor was built using closure actions, which are new in the latest Ember v1.13.0 release. This blog (http://alexdiliberto.com/posts/ember-closure-actions/) compares the old and new approaches to sending actions well. Let me know if you still have questions after reading it!
