### ISSUE TITLE
Modifying value

### ISSUE THREAD

**Issue by zkwentz** [lynnetye/ember-trix-editor#4]
So with data down actions up here, how do I actually change the value of the value I pass in? Right now I just get a jquery event back, I have no easily accessible updated value.

**Comment by zkwentz** [comment]
For those possibly struggling with this, this is my current solution:

```coffeescript
actions:
  onChange: (event) ->
    model = @get('model')
    if !!model
      model.set('body',event.target.value)
```

**Comment by lynnetye** [comment]
@zkwentz Sorry for the delay!

Take a look at the example in the README. You can access the properties of the original event, such as the target, from this. So in your case `jqEvent.originalEvent.target.value`.

**Comment by zkwentz** [comment]
Thanks @lynnetye :+1:
