### ISSUE TITLE
How do I clear the editor from outside?

### ISSUE THREAD

**Issue by brendanoh** [lynnetye/ember-trix-editor#8]
So I really like the addon and I am using this addon in a chat client like so:

<img width="973" alt="screen shot 2016-02-01 at 10 00 28 pm" src="https://cloud.githubusercontent.com/assets/3473461/12738550/aa062310-c92f-11e5-91d9-2229a3a83f7e.png">

So when they click 'send message' it takes the message and saves it and it populates above. All good. But I cannot figure out how to clear the editor itself which is what I would like to do.

Suggestions?

**Comment by lynnetye** [comment]
@brendanoh You can clear the input w/ `$('.trix-editor').val('')`, so it might be easiest to write a function that does this and calling it whenever the user hits enter or clicks on the "send message" button.

**Comment by brendanoh** [comment]
Awesome thanks @lynnetye
